import { StyleSheet } from 'react-native';

import { Colors, Fonts } from '../../Property';

const styles = StyleSheet.create({
  defaultContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  defaultButton: {
    backgroundColor: Colors.primary,
    height: 56,
    width: '100%',
  },
  defaultText: {
    color: Colors.background,
    fontSize: Fonts.size.medium,
    fontFamily: Fonts.type.base,
  },
  defaultIcon: {
    color: Colors.background,
    padding: 8,
  },
  roundedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundedButton: {
    backgroundColor: Colors.header,
    height: 36,
    width: 176,
    borderWidth: 1,
    borderColor: Colors.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundedButtonAzure: {
    height: 56,
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.background,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundedButtonWarmRed: {
    height: 56,
    width: '100%',
    borderWidth: 1,
    borderColor: Colors.backgroundColor,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roundedButtonWarmRedDisableBorder: {
    borderColor: Colors.background,
  },
  roundedText: {
    color: Colors.background,
    fontSize: Fonts.size.medium,
    fontFamily: Fonts.type.base,
    fontWeight: Fonts.weight.bold,
  },
  pickerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pickerButton: {
    width: 56,
    height: '100%',
    borderWidth: 1,
    borderColor: Colors.greyButton,
    paddingTop: 0,
    paddingBottom: 0,
  },
  pickerButtonLeft: {
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
  },
  pickerButtonRight: {
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
  },
  pickerText: {
    color: Colors.black_61,
    fontSize: Fonts.size.backgroundColor6,
    fontFamily: Fonts.type.base,
  },
  boxRoundedInnerWrapper: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    width: '100%',
  },
  boxRoundedButtonEnabled: {
    height: 56,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 0,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: Colors.header,
    backgroundColor: Colors.header,
  },

  boxReloadJenius: {
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom: 0,
        paddingLeft: 0,
    height: 32,
    width: 65,
    borderWidth: 1,
    borderColor: Colors.header,
    borderRadius: 4,
    backgroundColor: Colors.background,
    elevation: 0,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 85,
  },

  boxRoundedButtonDisabled: {
    height: 56,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 0,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: Colors.header,
    backgroundColor: Colors.header,
    opacity: 0.5,
  },
  roundedDiscountButton: {
    backgroundColor: Colors.header,
    height: 56,
    borderWidth: 1,
    borderColor: Colors.header,
    borderRadius: 4,
    elevation: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    minWidth: 150,
  },
  roundedDiscountFilledButton: {
    backgroundColor: Colors.header,
    height: 56,
    borderWidth: 1,
    borderColor: Colors.header,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    elevation: 0,
    paddingTop: 0,
    paddingBottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  roundedDiscountClearButton: {
    backgroundColor: Colors.header,
    height: 56,
    borderWidth: 1,
    borderColor: Colors.header,
    borderTopRightRadius: 4,
    borderBottomRightRadius: 4,
    elevation: 0,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    width: 40,
  },
  roundedDiscountDivider: {
    width: 1,
    height: 56,
    marginLeft: 5,
    marginRight: 5,
    backgroundColor: Colors.header,
  },
  fullRectangularWrapper: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullRectangularButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.snow,
  },
  greyButton: {
    borderColor: Colors.shadowBG,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.background,
    elevation: 0,
  },
  ButtonDownloadEnable: {
    width: 36,
    height: 56,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 3,
    borderColor: Colors.primary,
    backgroundColor: Colors.snow,
  },
  ButtonDownloadEnableOpacity: {
    opacity: 0.5,
  },
  ButtonDownloadDisable: {
    width: 36,
    height: 56,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 3,
    borderColor: Colors.background,
    backgroundColor: Colors.background,
  },
  IconDark: {
    color: Colors.header,
    padding: 5,
  },
  IconWarmRed: {
    color: Colors.header,
    padding: 5,
  },
  roundedDarkWrapper: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lightWithDisabledButtonEnabled: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    width: 100,
    marginTop: 19,
    height: 36,
    borderRadius: 4,
    marginBottom: 27,
    backgroundColor: Colors.primary,
  },
  lightWithDisabledButtonDisabled: {
    backgroundColor: Colors.background,
  },
  uploadWrapper: {
    width: 100,
  },
  uploadButtonBase: {
    height: 56,
    width: 100,
    flexDirection: 'column-reverse',
    alignItems: 'flex-start',
    paddingLeft: 20,
    borderWidth: 1,
    borderRadius: 4,
  },
  uploadIconStyle: {
    marginRight: 10,
  },
  uploadDefaultButton: {
    borderColor: Colors.background,
    backgroundColor: Colors.background,
    color: Colors.dark,
  },
  uploadheaderButton: {
    borderColor: Colors.greyButton,
    backgroundColor: Colors.background,
    color: Colors.dark,
  },
  uploadErrorButton: {
    borderColor: Colors.red,
    backgroundColor: Colors.light,
    color: Colors.dark,
  },
  buttonInnerStyle: {
    flexDirection: 'row-reverse',
  },
  roundedBoxAddWrapper: {
    height: 56,
    width: 36,
    flexDirection: 'row',
    alignItems: 'center',
  },
  roundedButtonBoxAdd: {
    height: 56,
    width: 36,
    borderWidth: 0,
  },
  iconBoxAdd: {
    fontFamily: Fonts.type.medium,
    fontSize: 30,
    color: Colors.header,
    paddingLeft: 15,
    paddingRight: 22,
  },
  iconButton: {
    fontSize: 30,
  },
});

export {
  styles as default,
};
